// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cingbjinmazwnemmmtip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpbmdiamlubWF6d25lbW1tdGlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwOTQ5MzYsImV4cCI6MjA2NDY3MDkzNn0.YbCga2Ojn7yxm9Jmm7Lcgw7mcz6y6EouzhhPsMcNcxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);